language: cpp

notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: xenial
      env: CMAKE_SHARED=on

    - os: linux
      dist: xenial
      env: CMAKE_SHARED=off

    - os: osx
      env: CMAKE_SHARED=off

    - os: windows
      env: CMAKE_SHARED=on

    - os: windows
      env: CMAKE_SHARED=off
  
  fast_finish: true

before_install:
  - if [ $TRAVIS_OS_NAME == windows ]; then MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y libx11-dev libxcb1-dev libx11-xcb-dev libxcb-randr0-dev libxcb-image0-dev libxrandr-dev libgl1-mesa-dev libudev-dev libxrandr-dev libfreetype6-dev libjpeg-dev; fi

before_script:
  - gcc --version
  - cmake --version
  - mkdir build
  - cd build
  - if [ $TRAVIS_OS_NAME == windows ]; then cmake -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS=$CMAKE_SHARED -DCMAKE_BUILD_TYPE=Release -DDUI_BUILD_TESTS=on ..; fi
  - if [ $TRAVIS_OS_NAME != windows ]; then cmake -DBUILD_SHARED_LIBS=$CMAKE_SHARED -DCMAKE_BUILD_TYPE=Release -DDUI_BUILD_TESTS=on ..; fi

script:
  - if [ $TRAVIS_OS_NAME == windows ]; then export PATH=$MSBUILD_PATH:$PATH && MSBuild.exe Project.sln -p:Configuration=Release -verbosity:minimal; fi
  - if [ $TRAVIS_OS_NAME == windows ]; then ctest -C Release --verbose; fi
  - if [ $TRAVIS_OS_NAME != windows ]; then make; fi
  - if [ $TRAVIS_OS_NAME != windows ]; then ctest --verbose; fi